[tool.poetry]
name = "connector-proxy"
version = "0.1.0"
description = ""
authors = ["Jon Herron <jon.herron@yahoo.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Flask = "*"

connector-bamboohr = {develop = true, path = "/home/jon/dev/connector-bamboohr"}
connector-xero = {develop = true, path = "/home/jon/dev/connector-xero"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
